import time

from fastapi import Request, Response
from loguru import logger
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint


class TimeRequest(BaseHTTPMiddleware):
    """
    Middleware class to measure the time taken to process a request. The time taken is logged using the logger.
    """

    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        """
        Dispatch method that measures the time taken to process a request.

        Args:
            request (Request): The incoming request.
            call_next (RequestResponseEndpoint): The next middleware or endpoint to call.

        Returns:
            Response: The response generated by the endpoint or middleware.
        """
        start_time = time.time()
        response = await call_next(request)
        response_time = time.time() - start_time
        logger.info(f"Request processed within {response_time} s")
        return response
